In [4]:
from google.colab import files

uploaded = files.upload()

Saving job_roles.csv to job_roles.csv
Saving skills_database.json to skills_database.json
Saving skills_list.csv to skills_list.csv
Saving test_resumes.json to test_resumes.json
Saving training_data.csv to training_data.csv

In [5]:
import os

os.listdir()

['.config',
 'job_roles.csv',
 'test_resumes.json',
 'training_data.csv',
 'skills_database.json',
 'skills_list.csv',
 'sample_data']

In [6]:
import pandas as pd

train_df = pd.read_csv("training_data.csv")

train_df.head()

,Resume ID,Resume Text,Education,Experience Years,Skills,Job Role,Category
0,R000000,Education: Bachelor's in Computer Science Expe...,Bachelor's in Computer Science,2,Market Research|Maven|Java|REST API|Spring Boo...,Java Backend Developer,Technology
1,R000001,Education: Master's in Microbiology Experience...,Master's in Microbiology,3,Agile|Data Analysis|Precision|Problem Solving|...,Microbiologist,Science & Research
2,R000002,Education: Apprenticeship Experience: 2 years ...,Apprenticeship,2,React|Customer Service|Technical Knowledge|Plu...,Plumber,Skilled Trades
3,R000003,Education: Bachelor's in Computer Science Expe...,Bachelor's in Computer Science,0,MySQL|Query Optimization|Symfony|Terraform|PHP...,PHP Developer,Technology
4,R000004,Education: Bachelor's in Design Experience: 3 ...,Bachelor's in Design,3,Problem Solving|Docker|Creativity|Scrum|Ansibl...,Art Director,Creative & Design

In [7]:
train_df.shape

(10000, 7)

In [8]:
train_df.columns

Index(['Resume ID', 'Resume Text', 'Education', 'Experience Years', 'Skills',
       'Job Role', 'Category'],
      dtype='object')

In [9]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Resume ID         10000 non-null  object
 1   Resume Text       10000 non-null  object
 2   Education         10000 non-null  object
 3   Experience Years  10000 non-null  int64
 4   Skills            10000 non-null  object
 5   Job Role          10000 non-null  object
 6   Category          10000 non-null  object
dtypes: int64(1), object(6)
memory usage: 547.0+ KB

In [10]:
train_df.isnull().sum()

Resume ID           0
Resume Text         0
Education           0
Experience Years    0
Skills              0
Job Role            0
Category            0
dtype: int64

In [11]:
import re
import pandas as pd

In [12]:
def clean_resume(text):

    text = str(text)

    # remove urls
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # remove email
    text = re.sub(r'\S+@\S+', ' ', text)

    # remove phone numbers
    text = re.sub(r'\d{10,}', ' ', text)

    # remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # lowercase
    text = text.lower()

    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [13]:
train_df["Cleaned_Resume"] = train_df["Resume Text"].apply(clean_resume)

In [14]:
train_df[["Resume Text", "Cleaned_Resume"]].head()

,Resume Text,Cleaned_Resume
0,Education: Bachelor's in Computer Science Expe...,education bachelor s in computer science exper...
1,Education: Master's in Microbiology Experience...,education master s in microbiology experience ...
2,Education: Apprenticeship Experience: 2 years ...,education apprenticeship experience years skil...
3,Education: Bachelor's in Computer Science Expe...,education bachelor s in computer science exper...
4,Education: Bachelor's in Design Experience: 3 ...,education bachelor s in design experience year...

In [15]:
train_df["Cleaned_Resume"][0]

'education bachelor s in computer science experience years skills market research maven java rest api spring boot microservices statistics sql'

In [16]:
skills_df = pd.read_csv("skills_list.csv")

skills_df.head()

   Skill Name     Category
0      Python  Programming
1        Java  Programming
2  JavaScript  Programming
3         C++  Programming
4          C#  Programming

In [17]:
skills_df.shape

(120, 2)

In [18]:
skills_df.columns

Index(['Skill Name', 'Category'], dtype='object')

In [19]:
skills_df.head(20)

         Skill Name         Category
0            Python      Programming
1              Java      Programming
2        JavaScript      Programming
3               C++      Programming
4                C#      Programming
5              Ruby      Programming
6               PHP      Programming
7                Go      Programming
8              Rust      Programming
9        TypeScript      Programming
10           Kotlin      Programming
11            Swift      Programming
12            Scala      Programming
13             Perl      Programming
14  Shell Scripting      Programming
15                R      Programming
16             HTML  Web Development
17              CSS  Web Development
18            React  Web Development
19           Vue.js  Web Development

In [20]:
import json

with open("skills_database.json", "r") as file:
    skills_db = json.load(file)

print(type(skills_db))

<class 'dict'>

In [21]:
# It can be also written as -> list(skills_db.keys())[:10]
skills_db

{'Programming': ['Python',
  'Java',
  'JavaScript',
  'C++',
  'C#',
  'Ruby',
  'PHP',
  'Go',
  'Rust',
  'TypeScript',
  'Kotlin',
  'Swift',
  'Scala',
  'Perl',
  'Shell Scripting',
  'R'],
 'Web Development': ['HTML',
  'CSS',
  'React',
  'Vue.js',
  'Angular',
  'Node.js',
  'Django',
  'Flask',
  'REST API',
  'GraphQL',
  'Responsive Design',
  'Web Accessibility',
  'SEO'],
 'Mobile Development': ['Android',
  'iOS',
  'React Native',
  'Flutter',
  'Mobile UI/UX',
  'Mobile Security',
  'App Testing'],
 'Cloud & DevOps': ['AWS',
  'Azure',
  'GCP',
  'Docker',
  'Kubernetes',
  'CI/CD',
  'Jenkins',
  'Terraform',
  'CloudFormation',
  'Ansible',
  'Microservices',
  'Serverless'],
 'Data Science & Analytics': ['Machine Learning',
  'Deep Learning',
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Data Analysis',
  'Statistics',
  'Pandas',
  'NumPy',
  'SQL',
  'Tableau',
  'Power BI',
  'Jupyter',
  'Python',
  'R'],
 'Database': ['SQL',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Oracle',
  'Cassandra',
  'Redis',
  'Database Design',
  'Query Optimization',
  'NoSQL'],
 'Soft Skills': ['Leadership',
  'Communication',
  'Problem Solving',
  'Critical Thinking',
  'Teamwork',
  'Time Management',
  'Adaptability',
  'Creativity',
  'Negotiation',
  'Mentoring',
  'Project Management',
  'Strategic Planning',
  'Decision Making'],
 'Business': ['Financial Analysis',
  'Business Development',
  'Market Research',
  'Strategic Planning',
  'Business Acumen',
  'Sales',
  'Marketing',
  'Budget Management',
  'P&L Management'],
 'Design': ['User Experience',
  'User Interface',
  'Graphic Design',
  'Web Design',
  'Adobe Creative Suite',
  'Figma',
  'Wireframing',
  'Prototyping'],
 'Cybersecurity': ['Penetration Testing',
  'Network Security',
  'Encryption',
  'Firewalls',
  'Security Protocols',
  'Risk Assessment',
  'Compliance',
  'Security Architecture'],
 'Professional': ['Project Management',
  'Agile',
  'Scrum',
  'Kanban',
  'Jira',
  'Confluence',
  'Documentation',
  'Technical Writing',
  'Presentation Skills']}

In [22]:
all_skills = set()

for skill in train_df["Skills"]:
    skill_list = str(skill).split("|")

    for s in skill_list:
        all_skills.add(s.strip().lower())

print("Total Skills:", len(all_skills))

Total Skills: 793

In [23]:
list(all_skills)[:50]

['platform knowledge',
 'vulnerability research',
 'coaching',
 'critical thinking',
 'psychological assessment',
 'kotlin',
 'ui/ux design',
 'supply planning',
 'graphics programming',
 'vision setting',
 'erlang',
 'hardware installation',
 'hand tools',
 'equipment maintenance',
 'decoration',
 'system architecture',
 'texturing',
 'database',
 'diagnosis',
 'legal knowledge',
 'team leadership',
 'analytical skills',
 'law enforcement',
 'drupal',
 'networking',
 'academic planning',
 'regular expressions',
 'drawing',
 'patience',
 'budget control',
 'functional programming',
 'security systems',
 'timeline management',
 'program design',
 'salesforce',
 'data analysis',
 'devops',
 'clinical data',
 'market intelligence',
 'safety',
 'technical documentation',
 'seo knowledge',
 'xml',
 'strategic hr',
 'tidyverse',
 'recipe development',
 'business operations',
 'typing',
 'ios development',
 'assessment']

In [24]:
def extract_skills(text):

    text = str(text).lower()

    detected_skills = []

    for skill in all_skills:

        if skill in text:
            detected_skills.append(skill)

    return list(set(detected_skills))

In [25]:
sample_resume = train_df["Cleaned_Resume"][0]

extract_skills(sample_resume)

['rest api',
 'spring boot',
 'sql',
 'maven',
 'r',
 'java',
 'research',
 'microservices',
 'statistics',
 'market research']

In [26]:
train_df["Extracted_Skills"] = train_df["Cleaned_Resume"].apply(extract_skills)

In [27]:
train_df[
    ["Job Role",
     "Skills",
     "Extracted_Skills"]
].head()

,Job Role,Skills,Extracted_Skills
0,Java Backend Developer,Market Research|Maven|Java|REST API|Spring Boo...,"[rest api, spring boot, sql, maven, r, java, r..."
1,Microbiologist,Agile|Data Analysis|Precision|Problem Solving|...,"[business development, analysis, agile, scala,..."
2,Plumber,React|Customer Service|Technical Knowledge|Plu...,"[technical knowledge, postgresql, creativity, ..."
3,PHP Developer,MySQL|Query Optimization|Symfony|Terraform|PHP...,"[analysis, php, api development, financial ana..."
4,Art Director,Problem Solving|Docker|Creativity|Scrum|Ansibl...,"[ansible, creativity, design, team leadership,..."

In [28]:
# job_title = "Data Scientist"

# required_skills = [
#     "python",
#     "sql",
#     "machine learning",
#     "pandas"
# ]

# job_description = """
# We are looking for a Data Scientist with strong knowledge
# of Python, SQL, Machine Learning, Pandas, Data Analysis,
# and Visualization.
# """

job_title = "Data Analyst"

required_skills = [
    "python",
    "excel",
    "power bi",
    "data analysis"
]

job_description = """
Looking for a Data Analyst with skills in
Excel, Power BI, Python and Data Analysis.
"""

In [29]:
clean_jd = clean_resume(job_description)

print(clean_jd)

looking for a data analyst with skills in excel power bi python and data analysis

In [30]:
jd_skills = extract_skills(clean_jd)

print(jd_skills)

['analysis', 'python', 'power bi', 'r', 'data analysis', 'excel']

In [31]:
def calculate_skill_match(candidate_skills,
                          required_skills):

    candidate_set = set(candidate_skills)

    required_set = set(required_skills)

    matched = candidate_set.intersection(required_set)

    score = (
        len(matched) /
        len(required_set)
    ) * 100

    return round(score,2)

In [32]:
candidate_skills = [
    "python",
    "sql",
    "pandas"
]

calculate_skill_match(
    candidate_skills,
    required_skills
)

25.0

In [33]:
candidate_skills = train_df[
    "Extracted_Skills"
][0]

calculate_skill_match(
    candidate_skills,
    required_skills
)

0.0

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
def calculate_resume_similarity(
    resume_text,
    job_description
):

    documents = [
        str(resume_text),
        str(job_description)
    ]

    tfidf = TfidfVectorizer()

    matrix = tfidf.fit_transform(documents)

    similarity = cosine_similarity(
        matrix[0:1],
        matrix[1:2]
    )

    return round(
        similarity[0][0] * 100,
        2
    )

In [36]:
calculate_resume_similarity(
    train_df["Cleaned_Resume"][0],
    clean_jd
)

np.float64(6.16)

In [37]:
train_df["Similarity_Score"] = (
    train_df["Cleaned_Resume"]
    .apply(
        lambda x:
        calculate_resume_similarity(
            x,
            clean_jd
        )
    )
)

In [38]:
train_df[
    ["Job Role",
     "Similarity_Score"]
].head()

                 Job Role  Similarity_Score
0  Java Backend Developer              6.16
1          Microbiologist             16.83
2                 Plumber              2.91
3           PHP Developer              9.26
4            Art Director              5.99

In [39]:
train_df["Skill_Match"] = (
    train_df["Extracted_Skills"]
    .apply(
        lambda x:
        calculate_skill_match(
            x,
            required_skills
        )
    )
)

In [40]:
train_df["Final_Score"] = (
    train_df["Skill_Match"] * 0.6
    +
    train_df["Similarity_Score"] * 0.4
)

In [41]:
train_df[
    [
        "Job Role",
        "Skill_Match",
        "Similarity_Score",
        "Final_Score"
    ]
].head()

                 Job Role  Skill_Match  Similarity_Score  Final_Score
0  Java Backend Developer          0.0              6.16        2.464
1          Microbiologist         25.0             16.83       21.732
2                 Plumber          0.0              2.91        1.164
3           PHP Developer          0.0              9.26        3.704
4            Art Director          0.0              5.99        2.396

In [42]:
ranked_candidates = train_df.sort_values(
    by="Final_Score",
    ascending=False
)

ranked_candidates.head()

,Resume ID,Resume Text,Education,Experience Years,Skills,Job Role,Category,Cleaned_Resume,Extracted_Skills,Similarity_Score,Skill_Match,Final_Score
5913,R005913,Education: Master's in Data Science Experience...,Master's in Data Science,2,Statistics|Data Analysis|Machine Learning|Adob...,Data Scientist,Technology,education master s in data science experience ...,"[analysis, python, tensorflow, power bi, sql, ...",35.81,75.0,59.324
9468,R009468,Education: Data Science Certificate Experience...,Data Science Certificate,2,R|Jupyter Notebooks|Data Analysis|Angular|Visu...,Jupyter Developer,Data & Analytics,education data science certificate experience ...,"[jupyter notebooks, analysis, python, angular,...",35.13,75.0,59.052
1574,R001574,Education: Bachelor's in IT Experience: 4 year...,Bachelor's in IT,4,Power BI|Tableau|Kubernetes|Excel|Data Analysi...,BI Analyst,Data & Analytics,education bachelor s in it experience years sk...,"[analysis, kubernetes, reporting, power bi, sq...",34.38,75.0,58.752
1455,R001455,Education: Data Science Certificate Experience...,Data Science Certificate,4,Documentation|Jupyter Notebooks|Data Analysis|...,Jupyter Developer,Data & Analytics,education data science certificate experience ...,"[jupyter notebooks, analysis, python, cloudfor...",33.98,75.0,58.592
9721,R009721,Education: Bachelor's in IT Experience: 4 year...,Bachelor's in IT,4,Power BI|Pandas|Tableau|SQL|Reporting|Creativi...,BI Analyst,Data & Analytics,education bachelor s in it experience years sk...,"[analysis, creativity, reporting, power bi, sq...",33.09,75.0,58.236

In [43]:
ranked_candidates = ranked_candidates.reset_index(drop=True)

ranked_candidates["Rank"] = (
    ranked_candidates.index + 1
)

In [44]:
ranked_candidates[
    [
        "Rank",
        "Job Role",
        "Final_Score"
    ]
].head(10)

   Rank           Job Role  Final_Score
0     1     Data Scientist       59.324
1     2  Jupyter Developer       59.052
2     3         BI Analyst       58.752
3     4  Jupyter Developer       58.592
4     5         BI Analyst       58.236
5     6         BI Analyst       58.236
6     7         BI Analyst       58.236
7     8         BI Analyst       58.236
8     9         BI Analyst       58.236
9    10         BI Analyst       58.236

In [45]:
def hiring_recommendation(score):

    if score >= 85:
        return "Strongly Recommend"

    elif score >= 70:
        return "Recommend"

    elif score >= 50:
        return "Consider"

    else:
        return "Reject"

In [46]:
ranked_candidates[
    "Recommendation"
] = ranked_candidates[
    "Final_Score"
].apply(
    hiring_recommendation
)

In [47]:
ranked_candidates[
    [
        "Rank",
        "Final_Score",
        "Recommendation"
    ]
].head(20)

    Rank  Final_Score Recommendation
0      1       59.324       Consider
1      2       59.052       Consider
2      3       58.752       Consider
3      4       58.592       Consider
4      5       58.236       Consider
5      6       58.236       Consider
6      7       58.236       Consider
7      8       58.236       Consider
8      9       58.236       Consider
9     10       58.236       Consider
10    11       58.236       Consider
11    12       57.772       Consider
12    13       57.772       Consider
13    14       57.772       Consider
14    15       57.772       Consider
15    16       57.772       Consider
16    17       57.772       Consider
17    18       57.772       Consider
18    19       57.772       Consider
19    20       57.552       Consider

In [48]:
top_candidates = ranked_candidates.head(10)

top_candidates[
    [
        "Rank",
        "Job Role",
        "Final_Score",
        "Recommendation"
    ]
]

   Rank           Job Role  Final_Score Recommendation
0     1     Data Scientist       59.324       Consider
1     2  Jupyter Developer       59.052       Consider
2     3         BI Analyst       58.752       Consider
3     4  Jupyter Developer       58.592       Consider
4     5         BI Analyst       58.236       Consider
5     6         BI Analyst       58.236       Consider
6     7         BI Analyst       58.236       Consider
7     8         BI Analyst       58.236       Consider
8     9         BI Analyst       58.236       Consider
9    10         BI Analyst       58.236       Consider

In [49]:
print("Total Candidates:",
      len(ranked_candidates))

print("\nTop Score:",
      ranked_candidates[
          "Final_Score"
      ].max())

print("\nAverage Score:",
      ranked_candidates[
          "Final_Score"
      ].mean())

Total Candidates: 10000

Top Score: 59.324

Average Score: 5.9549076

In [50]:
def generate_explanation(candidate_skills,
                         required_skills,
                         similarity_score,
                         final_score):

    candidate_set = set(candidate_skills)

    required_set = set(required_skills)

    matched_skills = list(
        candidate_set.intersection(required_set)
    )

    missing_skills = list(
        required_set - candidate_set
    )

    recommendation = hiring_recommendation(
        final_score
    )

    return {
        "Matched Skills": matched_skills,
        "Missing Skills": missing_skills,
        "Similarity Score": similarity_score,
        "Final Score": final_score,
        "Recommendation": recommendation
    }

In [51]:
candidate = ranked_candidates.iloc[0]

explanation = generate_explanation(
    candidate["Extracted_Skills"],
    required_skills,
    candidate["Similarity_Score"],
    candidate["Final_Score"]
)

explanation

{'Matched Skills': ['data analysis', 'power bi', 'python'],
 'Missing Skills': ['excel'],
 'Similarity Score': np.float64(35.81),
 'Final Score': np.float64(59.324),
 'Recommendation': 'Consider'}

In [52]:
candidate = ranked_candidates.iloc[0]

print("===== HIREGENIUS AI REPORT =====")

print("\nRank:",
      candidate["Rank"])

print("\nRecommendation:",
      hiring_recommendation(
          candidate["Final_Score"]
      ))

print("\nFinal Score:",
      round(candidate["Final_Score"],2))

print("\nMatched Skills:")

for skill in explanation["Matched Skills"]:
    print("✓", skill)

print("\nMissing Skills:")

for skill in explanation["Missing Skills"]:
    print("✗", skill)

===== HIREGENIUS AI REPORT =====

Rank: 1

Recommendation: Consider

Final Score: 59.32

Matched Skills:
✓ data analysis
✓ power bi
✓ python

Missing Skills:
✗ excel

In [53]:
ranked_candidates["AI_Confidence"] = (
    ranked_candidates["Similarity_Score"] * 0.7
    +
    ranked_candidates["Skill_Match"] * 0.3
)

In [54]:
def get_strengths(matched_skills):

    if len(matched_skills) >= 5:
        return "Strong Technical Match"

    elif len(matched_skills) >= 3:
        return "Good Skill Alignment"

    else:
        return "Limited Skill Match"

In [55]:
def get_weaknesses(missing_skills):

    if len(missing_skills) >= 4:
        return "Several Important Skills Missing"

    elif len(missing_skills) >= 2:
        return "Moderate Skill Gaps"

    else:
        return "Minor Skill Gaps"

In [56]:
matched = explanation["Matched Skills"]
missing = explanation["Missing Skills"]

print(
    "Strength:",
    get_strengths(matched)
)

print(
    "Weakness:",
    get_weaknesses(missing)
)

Strength: Good Skill Alignment
Weakness: Minor Skill Gaps

In [57]:
import plotly.express as px
import plotly.graph_objects as go

In [58]:
fig = px.histogram(
    ranked_candidates,
    x="Final_Score",
    nbins=20,
    title="Candidate Score Distribution"
)

fig.show()

In [59]:
recommendation_counts = (
    ranked_candidates["Recommendation"]
    .value_counts()
    .reset_index()
)

recommendation_counts.columns = [
    "Recommendation",
    "Count"
]

fig = px.pie(
    recommendation_counts,
    values="Count",
    names="Recommendation",
    title="Hiring Recommendation Distribution"
)

fig.show()

In [60]:
top_roles = (
    ranked_candidates["Job Role"]
    .value_counts()
    .head(10)
    .reset_index()
)

top_roles.columns = [
    "Job Role",
    "Count"
]

fig = px.bar(
    top_roles,
    x="Job Role",
    y="Count",
    title="Top Job Roles"
)

fig.show()

In [61]:
from collections import Counter

all_candidate_skills = []

for skills in ranked_candidates["Extracted_Skills"]:
    all_candidate_skills.extend(skills)

skill_counts = Counter(
    all_candidate_skills
)

top_skills = pd.DataFrame(
    skill_counts.most_common(15),
    columns=["Skill","Count"]
)

top_skills.head()

             Skill  Count
0                r  10000
1    communication   4084
2  problem solving   3601
3       management   3096
4           design   2048

In [62]:
fig = px.bar(
    top_skills,
    x="Skill",
    y="Count",
    title="Top Skills Distribution"
)

fig.show()

In [63]:
top10 = ranked_candidates.head(10)

fig = px.bar(
    top10,
    x="Rank",
    y="Final_Score",
    hover_data=["Job Role"],
    title="Top 10 Candidates"
)

fig.show()

In [64]:
required_set = set(required_skills)

missing_skill_counter = {}

for skills in ranked_candidates[
    "Extracted_Skills"
]:

    missing = required_set - set(skills)

    for skill in missing:

        missing_skill_counter[
            skill
        ] = (
            missing_skill_counter
            .get(skill,0)
            + 1
        )

In [65]:
gap_df = pd.DataFrame(
    list(
        missing_skill_counter.items()
    ),
    columns=[
        "Skill",
        "Missing Count"
    ]
)

In [66]:
fig = px.bar(
    gap_df,
    x="Skill",
    y="Missing Count",
    title="Skill Gap Analysis"
)

fig.show()

In [67]:
print(
    "Total Candidates:",
    len(ranked_candidates)
)

print(
    "Average Score:",
    round(
        ranked_candidates[
            "Final_Score"
        ].mean(),
        2
    )
)

print(
    "Top Score:",
    round(
        ranked_candidates[
            "Final_Score"
        ].max(),
        2
    )
)

Total Candidates: 10000
Average Score: 5.95
Top Score: 59.32

In [68]:
def get_best_candidate():

    best = ranked_candidates.iloc[0]

    return f"""
🏆 Best Candidate

Rank: {best['Rank']}

Job Role: {best['Job Role']}

Final Score: {round(best['Final_Score'],2)}

Recommendation: {best['Recommendation']}
"""

In [69]:
print(get_best_candidate())

🏆 Best Candidate

Rank: 1

Job Role: Data Scientist

Final Score: 59.32

Recommendation: Consider

In [70]:
def generate_candidate_summary(candidate):

    return f"""
Candidate Summary

Job Role:
{candidate['Job Role']}

Final Score:
{round(candidate['Final_Score'],2)}

Skill Match:
{round(candidate['Skill_Match'],2)}%

Resume Similarity:
{round(candidate['Similarity_Score'],2)}%

Recommendation:
{candidate['Recommendation']}
"""

In [71]:
candidate = ranked_candidates.iloc[0]

print(
    generate_candidate_summary(candidate)
)

Candidate Summary

Job Role:
Data Scientist

Final Score:
59.32

Skill Match:
75.0%

Resume Similarity:
35.81%

Recommendation:
Consider

In [72]:
question_bank = {

    "python":[
        "What are Python decorators?",
        "Explain list vs tuple.",
        "What is Pandas?"
    ],

    "sql":[
        "What is JOIN?",
        "Difference between WHERE and HAVING?",
        "Explain normalization."
    ],

    "machine learning":[
        "What is overfitting?",
        "Explain bias vs variance.",
        "What is cross validation?"
    ],

    "java":[
        "Explain OOP concepts.",
        "What is JVM?",
        "Difference between JDK and JRE?"
    ]
}

In [73]:
def generate_interview_questions(
        skills):

    questions = []

    for skill in skills:

        skill = skill.lower()

        if skill in question_bank:

            questions.extend(
                question_bank[skill]
            )

    return questions

In [74]:
candidate = ranked_candidates.iloc[0]

questions = generate_interview_questions(
    candidate["Extracted_Skills"]
)

for q in questions:
    print("•", q)

• What are Python decorators?
• Explain list vs tuple.
• What is Pandas?
• What is JOIN?
• Difference between WHERE and HAVING?
• Explain normalization.
• What is overfitting?
• Explain bias vs variance.
• What is cross validation?

In [75]:
def missing_skill_analysis(
        candidate_skills,
        required_skills):

    missing = list(
        set(required_skills)
        -
        set(candidate_skills)
    )

    return missing

In [76]:
candidate = ranked_candidates.iloc[0]

missing_skill_analysis(
    candidate["Extracted_Skills"],
    required_skills
)

['excel']

In [77]:
def ai_recruiter_advice(candidate):

    score = candidate["Final_Score"]

    if score >= 85:

        return """
Strong candidate.
Recommend immediate interview.
High alignment with job requirements.
"""

    elif score >= 70:

        return """
Good candidate.
Suitable for technical screening.
"""

    elif score >= 50:

        return """
Moderate fit.
Requires further evaluation.
"""

    else:

        return """
Not recommended.
Large skill gap detected.
"""

In [78]:
candidate = ranked_candidates.iloc[0]

print(
    ai_recruiter_advice(candidate)
)

Moderate fit.
Requires further evaluation.

In [79]:
def recruiter_chat(query):

    query = query.lower()

    if "best candidate" in query:

        return get_best_candidate()

    elif "top candidate" in query:

        return get_best_candidate()

    elif "summary" in query:

        return generate_candidate_summary(
            ranked_candidates.iloc[0]
        )

    else:

        return "Please ask a recruitment-related question."

In [80]:
recruiter_chat(
    "who is the best candidate"
)

'\n🏆 Best Candidate\n\nRank: 1\n\nJob Role: Data Scientist\n\nFinal Score: 59.32\n\nRecommendation: Consider\n'

In [81]:
!pip install pdfplumber
!pip install python-docx

Collecting pdfplumber
  Downloading pdfplumber-0.11.10-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 2.3 MB/s eta 0:00:00
Collecting pdfminer.six==20260107 (from pdfplumber)
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting Pillow>=12.2.0 (from pdfplumber)
  Downloading pillow-12.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pypdfium2>=5.9.0 (from pdfplumber)
  Downloading pypdfium2-5.10.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/70.3 kB 4.3 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20260107->pdfplumber) (3.4.7)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20260107->pdfplumber) (48.0.1)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Downloading pdfplumber-0.11.10-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 3.5 MB/s eta 0:00:00
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 60.4 MB/s eta 0:00:00
Downloading pillow-12.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 63.8 MB/s eta 0:00:00
Downloading pypdfium2-5.10.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 61.5 MB/s eta 0:00:00
Installing collected packages: pypdfium2, Pillow, pdfminer.six, pdfplumber
  Attempting uninstall: Pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.2.0 which is incompatible.
Successfully installed Pillow-12.2.0 pdfminer.six-20260107 pdfplumber-0.11.10 pypdfium2-5.10.1
Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.1.1)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (4.15.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 13.2 MB/s eta 0:00:00
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0

In [82]:
import pdfplumber
import docx

In [83]:
def extract_text_from_pdf(pdf_path):

    text = ""

    with pdfplumber.open(pdf_path) as pdf:

        for page in pdf.pages:

            page_text = page.extract_text()

            if page_text:
                text += page_text + "\n"

    return text

In [84]:
def extract_text_from_docx(docx_path):

    doc = docx.Document(docx_path)

    text = ""

    for para in doc.paragraphs:

        text += para.text + "\n"

    return text

In [85]:
from google.colab import files

uploaded = files.upload()

Saving Sample_Resume.pdf to Sample_Resume.pdf

In [86]:
resume_text = extract_text_from_pdf(
    "Sample_Resume.pdf"
)

print(resume_text[:1000])

In [87]:
clean_resume_text = clean_resume(
    resume_text
)

print(clean_resume_text[:500])

In [88]:
candidate_skills = extract_skills(
    clean_resume_text
)

print(candidate_skills)

[]

In [89]:
skill_match = calculate_skill_match(
    candidate_skills,
    required_skills
)

print(skill_match)

0.0

In [90]:
similarity = calculate_resume_similarity(
    clean_resume_text,
    clean_jd
)

print(similarity)

0.0

In [91]:
final_score = (
    skill_match * 0.6
    +
    similarity * 0.4
)

print(final_score)

0.0

In [92]:
recommendation = hiring_recommendation(
    final_score
)

print(recommendation)

Reject

In [93]:
print("Skills:", candidate_skills)
print("Skill Match:", skill_match)
print("Similarity:", similarity)
print("Final Score:", final_score)
print("Recommendation:", recommendation)

Skills: []
Skill Match: 0.0
Similarity: 0.0
Final Score: 0.0
Recommendation: Reject

In [94]:
print(resume_text[:2000])

In [95]:
!apt-get install poppler-utils -y
!apt-get install tesseract-ocr -y

!pip install pdf2image
!pip install pytesseract

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 186 kB of archives.
After this operation, 697 kB of additional disk space will be used.
Ign:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.12
Err:1 http://security.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.12
  404  Not Found [IP: 104.20.28.246 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/poppler/poppler-utils_22.02.0-2ubuntu0.12_amd64.deb  404  Not Found [IP: 104.20.28.246 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from pdf2image) (12.2.0)
Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Installing collected packages: pdf2image
Successfully installed pdf2image-1.17.0
Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (26.2)
Requirement already satisfied: Pillow>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (12.2.0)
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Installing collected packages: pytesseract
Successfully installed pytesseract-0.3.13

In [96]:
from pdf2image import convert_from_path
import pytesseract

In [97]:
def extract_text_ocr(pdf_path):

    pages = convert_from_path(pdf_path)

    text = ""

    for page in pages:
        page_text = pytesseract.image_to_string(page)
        text += page_text + "\n"

    return text

In [98]:
import os

os.listdir()

['.config',
 'job_roles.csv',
 'Sample_Resume.pdf',
 'test_resumes.json',
 'training_data.csv',
 'skills_database.json',
 'skills_list.csv',
 'sample_data']

In [99]:
!apt-get update
!apt-get install -y poppler-utils
!apt-get install -y tesseract-ocr

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:5 https://cli.github.com/packages stable InRelease [3,917 B]
Get:6 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,495 kB]
Get:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,612 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,361 kB]
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,026 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [82.8 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,307 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,221 kB]
Get:17 https://cli.github.com/packages stable/main amd64 Packages [354 B]
Get:18 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Get:19 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.4 MB]
Get:20 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,070 kB]
Get:21 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.6 kB]
Fetched 40.1 MB in 4s (9,429 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libpoppler-dev libpoppler-private-dev libpoppler118
Recommended packages:
  poppler-data
The following NEW packages will be installed:
  poppler-utils
The following packages will be upgraded:
  libpoppler-dev libpoppler-private-dev libpoppler118
3 upgraded, 1 newly installed, 0 to remove and 45 not upgraded.
Need to get 1,471 kB of archives.
After this operation, 697 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpoppler-private-dev amd64 22.02.0-2ubuntu0.13 [198 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpoppler-dev amd64 22.02.0-2ubuntu0.13 [5,186 B]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpoppler118 amd64 22.02.0-2ubuntu0.13 [1,081 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.13 [186 kB]
Fetched 1,471 kB in 0s (7,966 kB/s)
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../libpoppler-private-dev_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking libpoppler-private-dev:amd64 (22.02.0-2ubuntu0.13) over (22.02.0-2ubuntu0.12) ...
Preparing to unpack .../libpoppler-dev_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking libpoppler-dev:amd64 (22.02.0-2ubuntu0.13) over (22.02.0-2ubuntu0.12) ...
Preparing to unpack .../libpoppler118_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking libpoppler118:amd64 (22.02.0-2ubuntu0.13) over (22.02.0-2ubuntu0.12) ...
Selecting previously unselected package poppler-utils.
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.13_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.13) ...
Setting up libpoppler118:amd64 (22.02.0-2ubuntu0.13) ...
Setting up poppler-utils (22.02.0-2ubuntu0.13) ...
Setting up libpoppler-dev:amd64 (22.02.0-2ubuntu0.13) ...
Setting up libpoppler-private-dev:amd64 (22.02.0-2ubuntu0.13) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.

In [100]:
!which pdfinfo

/usr/bin/pdfinfo

In [101]:
resume_text = extract_text_ocr(
    "Sample_Resume.pdf"
)

In [102]:
print(resume_text[:1000])

CONTACT

& +91-98765432XX
&% riya.sharma@email.com
Q Location (City, State)

 linkedin.com/in/riyasharma

CERTIFICATIONS

¢ Google Data Analytics
Professional Certificate

¢ Advanced Excel (Microsoft)

LANGUAGES

e English (Fluent)
¢ Hindi (Fluent)

Nh Oe 7

COMPUTER SCIENCE GRADUATE





Motivated Computer Science graduate eager to apply
programming and analytical skills in a dynamic organization to
contribute to impactful projects

e CAREER OBJECTIVE

KEY SKILLS

¢ Data Analysis: Excel, SOL, Power BI
¢ Communication & Teamwork

¢ Problem-Solving & Critical Thinking

EDUCATION



¢ B.Tech in Computer Science | XYZ University | 2024
© CGPA: 8.5/10

| ¢ Programming: Python, Java, C++

Library Management System (Java): Developed
Con sshpinossici tvdts. cbs bladi mpaigbor syet thom Hamsges sloptent
tin Andakem, studens records.

Data Visualization Dashboard (Power BI):

9 ACADEMIC PROJECTS

Built an interactive dashboard to analyze student performance.

© Shine.com.All rights reser

In [103]:
clean_resume_text = clean_resume(resume_text)

In [104]:
candidate_skills = extract_skills(clean_resume_text)

print(candidate_skills)

['analysis', 'go', 'problem solving', 'critical thinking', 'data visualization', 'teamwork', 'management', 'r', 'excel', 'analytical skills', 'cad', 'performance', 'visualization', 'python', 'power bi', 'organization', 'communication', 'java', 'data analysis', 'analytics']

In [105]:
skill_match = calculate_skill_match(
    candidate_skills,
    required_skills
)

print(skill_match)

100.0

In [106]:
similarity = calculate_resume_similarity(
    clean_resume_text,
    clean_jd
)

print(similarity)

25.81

In [107]:
final_score = (
    skill_match * 0.6 +
    similarity * 0.4
)

print(final_score)

70.324

In [108]:
recommendation = hiring_recommendation(final_score)

print(recommendation)

Recommend

In [109]:
print(candidate_skills)

['analysis', 'go', 'problem solving', 'critical thinking', 'data visualization', 'teamwork', 'management', 'r', 'excel', 'analytical skills', 'cad', 'performance', 'visualization', 'python', 'power bi', 'organization', 'communication', 'java', 'data analysis', 'analytics']

In [110]:
skills_df.head(50)

           Skill Name                  Category
0              Python               Programming
1                Java               Programming
2          JavaScript               Programming
3                 C++               Programming
4                  C#               Programming
5                Ruby               Programming
6                 PHP               Programming
7                  Go               Programming
8                Rust               Programming
9          TypeScript               Programming
10             Kotlin               Programming
11              Swift               Programming
12              Scala               Programming
13               Perl               Programming
14    Shell Scripting               Programming
15                  R               Programming
16               HTML           Web Development
17                CSS           Web Development
18              React           Web Development
19             Vue.js           Web Development
20            Angular           Web Development
21            Node.js           Web Development
22             Django           Web Development
23              Flask           Web Development
24           REST API           Web Development
25            GraphQL           Web Development
26  Responsive Design           Web Development
27  Web Accessibility           Web Development
28                SEO           Web Development
29            Android        Mobile Development
30                iOS        Mobile Development
31       React Native        Mobile Development
32            Flutter        Mobile Development
33       Mobile UI/UX        Mobile Development
34    Mobile Security        Mobile Development
35        App Testing        Mobile Development
36                AWS            Cloud & DevOps
37              Azure            Cloud & DevOps
38                GCP            Cloud & DevOps
39             Docker            Cloud & DevOps
40         Kubernetes            Cloud & DevOps
41              CI/CD            Cloud & DevOps
42            Jenkins            Cloud & DevOps
43          Terraform            Cloud & DevOps
44     CloudFormation            Cloud & DevOps
45            Ansible            Cloud & DevOps
46      Microservices            Cloud & DevOps
47         Serverless            Cloud & DevOps
48   Machine Learning  Data Science & Analytics
49      Deep Learning  Data Science & Analytics

In [111]:
def extract_skills(text):

    skills_db = [
        "python",
        "java",
        "c++",
        "sql",
        "excel",
        "power bi",
        "machine learning",
        "data analysis",
        "pandas",
        "numpy",
        "tensorflow",
        "deep learning"
    ]

    text = text.lower()

    found_skills = []

    for skill in skills_db:

        if skill.lower() in text:
            found_skills.append(skill)

    return list(set(found_skills))

In [112]:
candidate_skills = extract_skills(resume_text)

print(candidate_skills)

['python', 'power bi', 'java', 'c++', 'data analysis', 'excel']

In [113]:
skill_match = calculate_skill_match(
    candidate_skills,
    required_skills
)

print("Skill Match:", skill_match)

Skill Match: 100.0

In [114]:
similarity = calculate_resume_similarity(
    clean_resume_text,
    clean_jd
)

print("Similarity:", similarity)

Similarity: 25.81

In [115]:
final_score = (
    skill_match * 0.6 +
    similarity * 0.4
)

print("Final Score:", final_score)

Final Score: 70.324

In [116]:
recommendation = hiring_recommendation(
    final_score
)

print("Recommendation:", recommendation)

Recommendation: Recommend

In [117]:
print(required_skills)

['python', 'excel', 'power bi', 'data analysis']

In [118]:
print(similarity)
print(final_score)
print(recommendation)

25.81
70.324
Recommend

In [119]:
!pip install reportlab

Collecting reportlab
  Downloading reportlab-5.0.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (12.2.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.7)
Downloading reportlab-5.0.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 25.5 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-5.0.0

In [120]:
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable
)

from reportlab.lib import colors

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from datetime import datetime

In [121]:
def get_strengths(candidate_skills):

    return candidate_skills[:5]


def get_missing_skills(
    candidate_skills,
    required_skills
):

    return list(
        set(required_skills)
        -
        set(candidate_skills)
    )


def ai_summary():

    if final_score >= 80:

        return """
Excellent candidate with strong alignment
to the job requirements.
Recommended for technical interview.
"""

    elif final_score >= 60:

        return """
Good candidate with relevant skills.
Recommended for further screening.
"""

    else:

        return """
Candidate has notable skill gaps.
Additional training is recommended.
"""

In [122]:
def generate_interview_questions(skills):

    questions = []

    if "python" in skills:
        questions.append(
            "Explain List vs Tuple in Python."
        )

    if "sql" in skills:
        questions.append(
            "Difference between JOIN and UNION?"
        )

    if "power bi" in skills:
        questions.append(
            "How do you create dashboards in Power BI?"
        )

    if "machine learning" in skills:
        questions.append(
            "Explain Bias vs Variance."
        )

    if len(questions) == 0:

        questions.append(
            "Tell us about yourself."
        )

    return questions

In [123]:
candidate_name = "Riya Sharma"
job_role = "Data Analyst"

In [124]:
print(candidate_name)
print(job_role)

print(candidate_skills)

print(skill_match)
print(similarity)
print(final_score)

print(recommendation)

Riya Sharma
Data Analyst
['python', 'power bi', 'java', 'c++', 'data analysis', 'excel']
100.0
25.81
70.324
Recommend

In [125]:
def create_progress_bar(score):

    width = int(score / 10)

    return (
        "█" * width
        +
        "░" * (10 - width)
    )

In [161]:
def generate_hiring_report_v5():

    pdf = SimpleDocTemplate(
        "HireGenius_Professional_Report_V5.pdf"
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        textColor=colors.HexColor("#131414"),
        alignment=1,
        fontSize=24
    )

    section_style = ParagraphStyle(
        "SectionStyle",
        parent=styles["Heading2"],
        textColor=colors.HexColor("#131414")
    )

    elements = []

    # ======================================
    # HEADER
    # ======================================

    subtitle_style = ParagraphStyle(
    "SubtitleStyle",
    parent=styles["Normal"],
    alignment=1,
    fontSize=12,
    textColor=colors.grey
)


    elements.append(
    Paragraph(
        "HIREGENIUS AI",
        title_style
    )
)

    elements.append(
    Paragraph(
        "AI-Powered Candidate Assessment Report",
        subtitle_style
    )
)

    elements.append(
    Spacer(1,8)
)

    elements.append(
        Spacer(1,15)
    )

    elements.append(
        HRFlowable(
            width="100%",
            thickness=1,
            color=colors.grey
        )
    )

    elements.append(
        Spacer(1,15)
    )

    # ======================================
    # CANDIDATE OVERVIEW
    # ======================================

    elements.append(
        Paragraph(
            "Candidate Overview",
            section_style
        )
    )

    overview = [

        ["Candidate Name", candidate_name],

        ["Applied Role", job_role],

        ["Report Date",
         datetime.now().strftime("%d-%m-%Y")]

    ]

    overview_table = Table(
        overview,
        colWidths=[180,220]
    )

    overview_table.setStyle(
        TableStyle([

            ('GRID',(0,0),(-1,-1),1,colors.grey),

            ('BACKGROUND',
             (0,0),
             (-1,-1),
             colors.whitesmoke)

        ])
    )

    elements.append(
        overview_table
    )

    elements.append(
        Spacer(1,20)
    )

    # ======================================
    # PERFORMANCE DASHBOARD
    # ======================================

    score_card = Table(



    [[
        f"""
    Final Score

    {round(final_score,2)}%

    {recommendation.upper()}
    """
        ]],

        colWidths=[400]

    )

    score_card.setStyle(

        TableStyle([

            ('BACKGROUND',
            (0,0),
            (-1,-1),
            colors.HexColor("#b6fcbf")),

            ('ALIGN',
            (0,0),
            (-1,-1),
            'CENTER'),

            ('BOX',
            (0,0),
            (-1,-1),
            2,
            colors.HexColor("#4e8a5d"))

        ])

    )

    elements.append(
        score_card
    )

    elements.append(
        Spacer(1,20)
    )

    elements.append(
        Paragraph(
            "Performance Dashboard",
            section_style
        )
    )

    rec_text = (
    "🟢 RECOMMEND"
    if recommendation.lower() == "recommend"
    else "🔴 REJECT"
)

    dashboard = [

        ["Metric","Score"],

        ["Skill Match",
         f"{round(skill_match,2)}%"],

        ["Similarity",
         f"{round(similarity,2)}%"],

        ["Final Score",
         f"{round(final_score,2)}%"],

        ["Recommendation", rec_text]

    ]

    dashboard_table = Table(
        dashboard,
        colWidths=[200,200]
    )

    dashboard_table.setStyle(
        TableStyle([

            ('BACKGROUND',
             (0,0),
             (-1,0),
             colors.HexColor("#322e36")),

            ('TEXTCOLOR',
             (0,0),
             (-1,0),
             colors.white),

            ('GRID',
             (0,0),
             (-1,-1),
             1,
             colors.black),

            ('ALIGN',
             (0,0),
             (-1,-1),
             'CENTER')

        ])
    )

    elements.append(
        dashboard_table
    )

    elements.append(
    Spacer(1,15)
)

    elements.append(
        Paragraph(
            f"Skill Match: {create_progress_bar(skill_match)} {round(skill_match,2)}%",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"Similarity: {create_progress_bar(similarity)} {round(similarity,2)}%",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"Final Score: {create_progress_bar(final_score)} {round(final_score,2)}%",
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1,20)
    )

    # ======================================
    # DETECTED SKILLS
    # ======================================

    elements.append(
        Paragraph(
            "Detected Skills",
            section_style
        )
    )

    skill_rows = [

    candidate_skills[i:i+3]

    for i in range(
        0,
        len(candidate_skills),
        3
    )

]

    skills_table = Table(
        skill_rows,
        colWidths=[120,120,120]
    )

    skills_table.setStyle(
        TableStyle([

            ('BACKGROUND',
            (0,0),
            (-1,-1),
           colors.HexColor("#d7dbd7")),

            ('GRID',
            (0,0),
            (-1,-1),
            1,
            colors.white),

            ('ALIGN',
            (0,0),
            (-1,-1),
            'CENTER')

        ])
    )

    elements.append(
        skills_table
    )
    elements.append(
            Spacer(1,15)
        )

    # ======================================
    # STRENGTHS
    # ======================================

    elements.append(
        Paragraph(
            "Strength Analysis",
            section_style
        )
    )

    strengths = get_strengths(
        candidate_skills
    )

    for s in strengths:

        elements.append(
            Paragraph(
                f"✓ {s}",
                styles["BodyText"]
            )
        )

    elements.append(
        Spacer(1,15)
    )

    # ======================================
    # MISSING SKILLS
    # ======================================

    elements.append(
        Paragraph(
            "Skill Gap Analysis",
            section_style
        )
    )

    missing = get_missing_skills(
        candidate_skills,
        required_skills
    )

    if len(missing) == 0:

        elements.append(
            Paragraph(
                "No critical skill gaps detected.",
                styles["BodyText"]
            )
        )

    else:

        for skill in missing:

            elements.append(
                Paragraph(
                    f"✗ {skill}",
                    styles["BodyText"]
                )
            )

    elements.append(
        Spacer(1,15)
    )



    # ======================================
    # AI VERDICT
    # ======================================



    elements.append(
        Paragraph(
            "AI Recruiter Verdict",
            section_style
        )
    )

    elements.append(
        Paragraph(
            ai_summary(),
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1,10)
    )

    recruiter_note = """
    <b>Recruiter Recommendation</b><br/><br/>

    • Candidate demonstrates strong alignment with the target role.<br/>
    • Relevant technical skills have been identified successfully.<br/>
    • Overall score indicates good hiring potential.<br/>
    • Recommended for the next stage of evaluation or technical interview.
    """

    note_data = [[
        Paragraph(
            recruiter_note,
            styles["BodyText"]
        )
    ]]

    note_table = Table(
        note_data,
        colWidths=[400]
    )

    note_table.setStyle(
        TableStyle([
            ('BACKGROUND',
             (0,0),
             (-1,-1),
             colors.whitesmoke),

            ('BOX',
             (0,0),
             (-1,-1),
             1,
             colors.grey),

            ('LEFTPADDING',
             (0,0),
             (-1,-1),
             10),

            ('RIGHTPADDING',
             (0,0),
             (-1,-1),
             10),

            ('TOPPADDING',
             (0,0),
             (-1,-1),
             10),

            ('BOTTOMPADDING',
             (0,0),
             (-1,-1),
             10)
        ])
    )

    elements.append(
        note_table
    )

    elements.append(
        Spacer(1,15)
    )

    # ======================================
    # INTERVIEW QUESTIONS
    # ======================================

    elements.append(
        Paragraph(
            "Recommended Interview Questions",
            section_style
        )
    )

    questions = generate_interview_questions(
        candidate_skills
    )

    for q in questions:

        elements.append(
            Paragraph(
                f"• {q}",
                styles["BodyText"]
            )
        )

    elements.append(
        Spacer(1,20)
    )

    # ======================================
    # FOOTER
    # ======================================

    elements.append(
        HRFlowable(
            width="100%",
            thickness=1,
            color=colors.grey
        )
    )

    elements.append(
        Spacer(1,10)
    )

    elements.append(
        Paragraph(
            "Generated by HireGenius AI Recruitment Platform",
            styles["Italic"]
        )
    )

    pdf.build(elements)

    print(
        "HireGenius V5 Report Generated Successfully"
    )

In [162]:
generate_hiring_report_v5()

HireGenius V5 Report Generated Successfully

In [163]:
from google.colab import files

files.download(
    "HireGenius_Professional_Report_V5.pdf"
)

In [172]:
def generate_resume_feedback(
    candidate_skills,
    required_skills,
    final_score
):

    feedback = []

    matched = list(
        set(candidate_skills)
        &
        set(required_skills)
    )

    missing = list(
        set(required_skills)
        -
        set(candidate_skills)
    )

    # ==========================
    # STRENGTHS
    # ==========================

    feedback.append("=== STRENGTHS ===")

    if len(matched):

        for skill in matched:

            feedback.append(
                f"✓ Strong in {skill}"
            )

    else:

        feedback.append(
            "No matching skills found."
        )

    feedback.append("")

    # ==========================
    # IMPROVEMENT AREAS
    # ==========================

    feedback.append(
        "=== IMPROVEMENT AREAS ==="
    )

    if len(missing):

        for skill in missing:

            feedback.append(
                f"✗ Learn {skill}"
            )

    else:

        feedback.append(
            "✓ No critical skill gaps detected."
        )

    feedback.append("")

    # ==========================
    # RECOMMENDATIONS
    # ==========================

    feedback.append(
        "=== RECOMMENDATIONS ==="
    )

    if final_score >= 80:

        feedback.append(
            "Candidate is highly aligned with the role."
        )

    elif final_score >= 60:

        feedback.append(
            "Candidate should strengthen missing skills."
        )

    else:

        feedback.append(
            "Candidate requires significant upskilling."
        )

    feedback.append(
        "Add real-world projects."
    )

    feedback.append(
        "Maintain GitHub portfolio."
    )

    return "\n".join(feedback)

In [173]:
feedback = generate_resume_feedback(
    candidate_skills,
    required_skills,
    final_score
)

print(feedback)

=== STRENGTHS ===
✓ Strong in data analysis
✓ Strong in power bi
✓ Strong in excel
✓ Strong in python

=== IMPROVEMENT AREAS ===
✓ No critical skill gaps detected.

=== RECOMMENDATIONS ===
Candidate should strengthen missing skills.
Add real-world projects.
Maintain GitHub portfolio.

In [174]:
def recruiter_chatbot(question):

    q = question.lower()

    missing = list(
        set(required_skills)
        -
        set(candidate_skills)
    )

    if "score" in q:

        return f"""
Candidate Final Score: {round(final_score,2)}%
Recommendation: {recommendation}
"""

    elif "skills" in q:

        return (
            "Detected Skills:\n\n"
            +
            ", ".join(candidate_skills)
        )

    elif "missing" in q:

        if len(missing) == 0:

            return (
                "No critical skill gaps detected."
            )

        return (
            "Missing Skills:\n\n"
            +
            ", ".join(missing)
        )

    elif "why" in q:

        return f"""
Candidate possesses
{len(candidate_skills)} identified skills.

Skill Match: {round(skill_match,2)}%

Final Score: {round(final_score,2)}%

Recommendation:
{recommendation}
"""

    elif "interview" in q:

        questions = generate_interview_questions(
            candidate_skills
        )

        return "\n".join(questions)

    elif "feedback" in q:

        return generate_resume_feedback(
            candidate_skills,
            required_skills,
            final_score
        )

    else:

        return """
You can ask:

• score
• skills
• missing skills
• recommendation
• why recommended
• interview questions
• feedback
"""

In [175]:
print(
    recruiter_chatbot(
        "why recommended"
    )
)

Candidate possesses
6 identified skills.

Skill Match: 100.0%

Final Score: 70.32%

Recommendation:
Recommend

In [176]:
print(
    recruiter_chatbot(
        "show feedback"
    )
)

=== STRENGTHS ===
✓ Strong in data analysis
✓ Strong in power bi
✓ Strong in excel
✓ Strong in python

=== IMPROVEMENT AREAS ===
✓ No critical skill gaps detected.

=== RECOMMENDATIONS ===
Candidate should strengthen missing skills.
Add real-world projects.
Maintain GitHub portfolio.

In [177]:
print(
    recruiter_chatbot(
        "give interview questions"
    )
)

Explain List vs Tuple in Python.
How do you create dashboards in Power BI?

In [179]:
while True:

    question = input("Recruiter: ")

    if question.lower() == "exit":

        print("Chat Closed")
        break

    print(
        recruiter_chatbot(
            question
        )
    )

Recruiter: skills
Detected Skills:

python, power bi, java, c++, data analysis, excel
Recruiter: exist

You can ask:

• score
• skills
• missing skills
• recommendation
• why recommended
• interview questions
• feedback

Recruiter: exit
Chat Closed

In [180]:
!pip install streamlit
!pip install pyngrok

Collecting streamlit
  Downloading streamlit-1.58.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (12.2.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.58.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 57.9 MB/s eta 0:00:00
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 49.7 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.2 streamlit-1.58.0
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.1.2

In [211]:
%%writefile app.py

import streamlit as st

st.set_page_config(
    page_title="HireGenius AI",
    page_icon="🚀",
    layout="wide"
)

st.title("🚀 HireGenius AI")

uploaded_file = st.file_uploader(
    "Upload Resume",
    type=["pdf"]
)

if uploaded_file is not None:

    with open(
        "uploaded_resume.pdf",
        "wb"
    ) as f:

        f.write(
            uploaded_file.getbuffer()
        )

    st.success(
        "Resume Uploaded Successfully"
    )

    st.write(
        "Saved as uploaded_resume.pdf"
    )

Overwriting app.py

In [212]:
!ls

app.py				       sample_data	     test_resumes.json
HireGenius_Professional_Report_V5.pdf  Sample_Resume.pdf     training_data.csv
job_roles.csv			       skills_database.json
logs.txt			       skills_list.csv

In [213]:
!streamlit run app.py &>/content/logs.txt &

In [216]:
!cat /content/logs.txt

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-06-22 17:59:41.399 Uvicorn server started on 0.0.0.0:8507

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8507
  Network URL: http://172.28.0.12:8507
  External URL: http://136.107.67.215:8507